version: '3.1'
services:
  server:
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - ./Lab:/home/moviesapp
    # command: "npm run dev"
    tty: true
  db:
    image: mongo:3.4-jessie
    volumes: 
      - ./dbs:/dbs
    ports:
      - 27017:27017